server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    # 引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug
    
dubbo:
  registry:
    address: zookeeper://192.168.255.130:2181?backup=192.168.255.130:2182,192.168.255.130:2183
  protocol:    name: root
    port: 2000    scan:    base-packages:    - com.jt.
    
