server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
dubbo:
  scan:
    basePackages: com.jt #包扫描
  application:
    name: comsumer-user  #定义服务名称
  registry:
    address: zookeeper://192.168.255.130:2181?backup=192.168.255.130:2182,192.168.255.130:2183

  